version: "3"
services:
  nginx:
    container_name: nginx
    image: ${NGINX_IMAGE}
    ports:
      - 80:80
      - 1717:1717
    environment:
      - NGINX_MAIN_PORT=80
      - NGINX_STATS_PORT=1717
      - FORWARD_PROTOCOL=proxy_pass
      - UWSGI_MAIN_PASS=http://localhost:3031
      - UWSGI_STATS_PASS=http://localhost:3032

  app:
    container_name: app
    image: ${FLASK_IMAGE}
    environment:
      - UWSGI_HTTP=:3031
      - UWSGI_STATS=:3032
      - UWSGI_STATS_HTTP=true
      - UWSGI_PROCESSES=${PROCCESS_NUM}
      - UWSGI_THREADS=${THREAD_NUM}
      