version: "3"
services:
  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - uwsgi_socket:/tmp
    ports:
      - 80:80
      - 1717:1717
    environment:
      - NGINX_MAIN_PORT=80
      - NGINX_STATS_PORT=1717
      - UWSGI_SOCKET=/tmp/uwsgi_main.sock
      - UWSGI_STATS=/tmp/uwsgi_stats.sock

  app:
    container_name: app
    build: ./app
    volumes:
      - uwsgi_socket:/tmp
      - ./app:/var/www/
    environment:
      - UWSGI_SOCKET=/tmp/uwsgi_main.sock
      - UWSGI_STATS=/tmp/uwsgi_stats.sock
      - UWSGI_PY_AUTORELOAD=1

volumes:
  uwsgi_socket:
